// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjrldlrndqqhjecnlkqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqcmxkbHJuZHFxaGplY25sa3F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4OTAyODcsImV4cCI6MjA3NDQ2NjI4N30.an53kP-qZx13lkAmKgpo8zmfwCfIlc1Ep6YwqlklSsM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});